import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:islami_app/Quran/item_sura_name.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class quranTap extends StatelessWidget {
  List<String> names = [
    '  al-Fatihah	',
    '	البَقَرَة	al-Baqarah	',
    '	آل عِمرَان	Al-Imran	',
    '	النِّسَاء	an-Nisa',
    ' 	المَائدة	al-Maidah	',
    '  	الأنعَام	al-An`am	',
    '	الأعرَاف	al-A`raf	',
    '	الأنفَال	al-Anfal	',
    ' 	التوبَة	at-Taubah',
    '	يُونس	Yunus',
    '	هُود	Hud	',
    '	يُوسُف	Yusuf	',
    '	الرَّعْد	ar-Ra`d	',
    '	إبراهِيم	Ibrahim	',
    '	الحِجْر	al-Hijr	',
    '	النَّحْل	an-Nahl	',
    ' 	الإسْرَاء	Al-Isra	',
    '	الكهْف	al-Kahf',
    '	مَريَم	Maryam	',
    ' 	طه	Ta Ha	',
    '	الأنبيَاء	al-Anbiya',
    ' 	الحَج	al-Hajj	',
    ' 	المُؤمنون	al-Muminun',
    '	النُّور	an-Nur	',
    ' 	الفُرْقان	al-Furqan	',
    '	الشُّعَرَاء	ash-Shu`araa',
    '	النَّمْل	an-Naml',
    '	القَصَص	al-Qasas	',
    ' 	العَنكبوت	al-`Ankabut	',
    '	الرُّوم	ar-Rum	',
    ' 	لقمَان	Luqman	',
    ' 	السَّجدَة	as-Sajdah	',
    '	الأحزَاب	al-Ahzab',
    '	سَبَأ	Saba',
    '	فَاطِر	Fatir	',
    ' 	يس	Ya Sin	',
    '	الصَّافات	as-Saffat	',
    '	ص	Sad	Saad	Sad',
    '	الزُّمَر	az-Zumar	',
    '	غَافِر	Ghafir	',
    '	فُصِّلَتْ	Fussilat	',
    '	الشُّورَى	ash-Shura',
    '	الزُّخْرُف	az-Zukhruf	',
    '  	الدُّخان	ad-Dukhan',
    ' 	الجاثِية	al-Jathiyah	',
    '	الأحقاف	al-Ahqaf	',
    ' 	مُحَمّد	Muhammad	',
    '	الفَتْح	al-Fath	',
    ' 	الحُجُرات	al-Hujurat',
    '	الذَّاريَات	ad-Dhariyat',
    'الطُّور	at-Tur',
    'النَّجْم	an-Najm		',
    '	القَمَر	al-Qamar		',
    '	الرَّحمن	ar-Rahman		',
    ' 	الواقِعَة	al-Waqi`ah',
    ' 	الحَديد	al-Hadid',
    '	المُجادَلة	al-Mujadilah',
    '	الحَشْر	al-Hashr',
    '	المُمتَحَنة		al-mumtaHanah	',
    '	الصَّف	as-Saff',
    '	الجُّمُعة	al-Jumu`ah',
    '	المُنافِقُون	al-Munafiqun',
    '	التَّغابُن	at-Taghabun',
    '	الطَّلاق	at-Talaq',
    '	التَّحْريم	at-Tahrim	',
    '  	المُلْك	al-Mulk	',
    '	القَلـََم	al-Qalam',
    '	الحَاقّـَة	al-Haqqah	',
    '	المَعارِج	al-Ma`arij',
    '  	نُوح	Nuh	nooH	Noah',
    '  	الجِنّ	al-Jinn',
    '	المُزَّمّـِل	al-Muzammil',
    '	المُدَّثــِّر	al-Mudathir',
    ' 	القِيامَة	al-Qiyamah',
    '	الإنسان	al-Insane',
    '	المُرسَلات	al-Mursalat',
    '	النـَّبأ	an-Naba',
    '	النـّازِعات	an-Nazi`at',
    '	عَبَس	`Abasa	`abasa',
    '	التـَّكْوير	at-Takwir	',
    ' 	الإنفِطار	al-Infitar',
    '	المُطـَفِّفين	Al-Mutaffifeen',
    ' 	الإنشِقاق	al-Inshiqaq',
    '	البُروج	al-Buruj',
    ' 	الطّارق	at-Tariq',
    'الأعلی	al-A`la	al-A`laa',
    ' 	الغاشِيَة	al-Ghashiya',
    ' 	الفَجْر	al-Fajr',
    '  	البَـلـَد	al-Balad',
    'الشــَّمْس	ash-Shams',
    ' 	اللـَّيل	al-Layl',
    ' 	الضُّحی	ad-Duha	aD-DuHaa',
    '  	الشَّرْح	ash-Sharh	ash-Sharh	',
    '	التـِّين	at-Tin	aT-Teen	',
    ' 	العَلـَق	al-`Alaq	',
    '  	القـَدر	al-qadr	',
    '  	البَيِّنَة	al-Bayyinah	',
    ' 	الزلزَلة	Az-Zalzala',
    ' 	العَادِيات	al-`Adiyat',
    '  	القارِعَة	al-Qari`ah',
    '	التَكاثـُر	at-Takathur',
    '	العَصْر	al-`Asr	',
    ' 	الهُمَزَة	al-Humazah',
    ' 	الفِيل	al-Fil',
    '	قـُرَيْش	al-Quraish',
    '  	المَاعُون	al-Ma`un	',
    '  	الكَوْثَر	al-Kauthar	',
    '  	الكَافِرُون	al-Kafirun	',
    '  	النـَّصر	an-Nasr	',
    '	المَسَد	Al-Masad',
    ' 	الإخْلَاص	al-Ikhlas',
    ' 	الفَلَق	al-Falaq	',
    ' 	النَّاس	an-Nas'
  ];
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Center(child: Image.asset('assets/images/quran_logo.png')),
        Divider(
          color: Theme.of(context).primaryColor,
          thickness: 3,
        ),
        Text(
          AppLocalizations.of(context)!.sura_name,
          style: Theme.of(context).textTheme.titleMedium,
        ),
        Divider(
          color: Theme.of(context).primaryColor,
          thickness: 3,
        ),
        Expanded(
          child: ListView.separated(
            separatorBuilder: ((context, index) {
              return Divider(
                color: Theme.of(context).primaryColor,
                thickness: 3,
              );
            }),
            itemBuilder: (context, index) {
              return itemSurah(
                name: names[index],
                index: index,
              );
            },
            itemCount: names.length,
          ),
        ),
      ],
    );
  }
}
